// Auto-generated type definitions
// Generated by auto-define tool


export type Date = unknown;

export type MessageEvent = unknown;

export class Worker {
  constructor() {
    // TODO: Implement constructor
  }

  // TODO: Add methods and properties
}

export type AgentResponse = unknown;

export type AgentPercept = unknown;

export interface UiMessage {
  id: string;
}

export type ErrorEvent = unknown;
